/**
 * Industry page data — high-demand verticals in the Australian market.
 */

export const INDUSTRY_PAGES = [
  {
    slug: "healthcare",
    title: "Healthcare",
    metaTitle: "Healthcare Web Development Australia | Clinics, Telehealth, Patient Portals",
    metaDescription: "Websites and apps for Australian healthcare — clinic sites, telehealth portals, patient booking systems. HIPAA-aware, fast, mobile-first. Fixed AUD pricing.",
    hero: "Healthcare websites that earn patient trust and simplify bookings.",
    intro: "Patients choose a clinic the same way they choose any service — they Google, glance at reviews, and book with whoever makes it easiest. A fast, mobile-friendly site with online booking converts more patients than a beautiful site with a buried phone number. We build healthcare sites that prioritise the patient journey: find → trust → book.",
    needs: [
      { title: "Online booking", body: "Let patients book appointments directly from your site, integrated with your calendar or practice management system." },
      { title: "Telehealth ready", body: "Video consultation pages and secure patient portals for remote care — essential in regional Australia." },
      { title: "Mobile-first design", body: "Most patients find you on a phone. Speed and usability on mobile directly affects whether they book." },
      { title: "Google Business Profile", body: "Local SEO and review management so you appear in 'doctor near me' and 'clinic near me' searches." },
      { title: "Compliance", body: "Privacy-aware builds with secure forms, encrypted data handling and clear consent flows." },
      { title: "Content that ranks", body: "Service pages targeting what patients actually search — conditions, treatments, costs." },
    ],
    stat: "70%+ of healthcare searches happen on mobile",
    relatedServices: ["Web Development", "AI & Automation", "Marketing & SEO"],
  },
  {
    slug: "real-estate",
    canonicalTo: '/real-estate-website-design/',
    title: "Real Estate",
    metaTitle: "Real Estate Web Development Australia | Agent Sites, Property Platforms",
    metaDescription: "Property listing websites, agent portfolios and buyer portals for Australian real estate. IDX-ready, fast search, mobile-first. Fixed AUD pricing.",
    hero: "Property sites that sell the listing — not just show it.",
    intro: "Buyers search properties online before they speak to an agent. Your website is the first inspection. We build real estate platforms with fast property search, high-quality gallery pages, and enquiry flows that capture serious buyers — so your online presence works as hard as your agents do.",
    needs: [
      { title: "Property listings", body: "Searchable, filterable property pages with maps, galleries and floor plans." },
      { title: "Agent profiles", body: "Individual agent pages with listings, bio, reviews and direct contact — building personal brand." },
      { title: "Lead capture", body: "Per-property enquiry forms, open home RSVPs and appraisal request flows." },
      { title: "IDX / API integration", body: "Connect to property data feeds so listings update automatically." },
      { title: "Premium design", body: "A site that signals the quality of the properties it represents." },
      { title: "Local SEO", body: "Suburb pages, area guides and schema markup so you rank for local searches." },
    ],
    stat: "92% of property buyers start their search online",
    relatedServices: ["Web Development", "Custom Software", "Marketing & SEO"],
  },
  {
    slug: "construction-trades",
    title: "Construction & Trades",
    metaTitle: "Tradie Website Design Australia | Plumber, Electrician, Builder Sites",
    metaDescription: "Websites for Australian tradies — plumbers, electricians, builders, landscapers. Click-to-call, quote forms, local SEO. Fixed pricing from AU$800.",
    hero: "Tradie sites built to win jobs, not awards.",
    intro: "When a pipe bursts at 2am, nobody scrolls — they call the first tradie who looks trustworthy and reachable. We build tradie websites around that moment: trust badges up front, click-to-call everywhere, quote forms that work on a phone, and local SEO so you show up in 'near me' searches.",
    needs: [
      { title: "Click-to-call", body: "A tap-to-call button on every section. The customer is on their phone — make calling effortless." },
      { title: "Quote request forms", body: "Short, mobile-friendly forms that capture the job details you need without losing the visitor." },
      { title: "Trust signals", body: "Licence numbers, insurance, Google reviews, trust badges — visible immediately, not buried in the footer." },
      { title: "Local SEO", body: "Location pages, LocalBusiness schema and Google Business Profile so you rank in your service area." },
      { title: "Fast loading", body: "A slow site loses emergency callers. Lighthouse 90+ on mobile is the minimum." },
      { title: "Service area pages", body: "One page per suburb or region you serve — each targeting the local search." },
    ],
    stat: "'Near me' searches for tradies grew 150% in AU",
    relatedServices: ["Web Development", "Marketing & SEO", "AI & Automation"],
  },
  {
    slug: "hospitality",
    title: "Hospitality",
    metaTitle: "Restaurant & Hospitality Web Development Australia | Menus, Bookings, Events",
    metaDescription: "Websites for Australian restaurants, cafés, bars and hotels. Direct bookings, live menus, event pages. No commission, no PDF menus. Fixed AUD pricing.",
    hero: "Keep your bookings direct and your menu off a PDF.",
    intro: "Every booking through a third-party platform costs you commission on a cover you earned yourself. We build hospitality sites with direct table booking, a live searchable menu (not a PDF), and event pages that drive walk-ins — keeping your margins intact and your brand in your hands.",
    needs: [
      { title: "Direct bookings", body: "Provider-agnostic booking so guests reserve directly — zero commission per cover." },
      { title: "Live menus", body: "Mobile-friendly, indexed menu pages that replace slow, unsearchable PDFs." },
      { title: "Event pages", body: "Promote events, special menus and seasonal offerings with dedicated landing pages." },
      { title: "Photography-led design", body: "Full-bleed imagery that captures the atmosphere of your venue." },
      { title: "Google Maps & reviews", body: "Local search presence with Restaurant schema, hours and location." },
      { title: "Ordering integration", body: "Connect online ordering for takeaway and delivery without third-party fees." },
    ],
    stat: "60% of diners check the menu online before visiting",
    relatedServices: ["Web Development", "Marketing & SEO", "Maintenance & Support"],
  },
  {
    slug: "education",
    title: "Education",
    metaTitle: "Education Web Development Australia | Schools, Courses, LMS Portals",
    metaDescription: "Websites and platforms for Australian education — school sites, online course platforms, student portals, LMS integration. Fixed AUD pricing.",
    hero: "Education platforms that actually get used.",
    intro: "Whether you are a school, training provider, or course creator, the website is how students find you and how they learn. We build education sites with clear course discovery, student portals, LMS integration and parent communication — designed for the people who actually use them, not just the admin who approves them.",
    needs: [
      { title: "Course catalogues", body: "Searchable, filterable course listings with intake dates, fees and application flows." },
      { title: "Student portals", body: "Secure login areas for enrolled students — grades, materials, schedules, communication." },
      { title: "LMS integration", body: "Connect to Moodle, Canvas, or build a custom learning interface." },
      { title: "Event & news", body: "School events, term dates, news and parent communication." },
      { title: "Accessibility", body: "WCAG-compliant builds so everyone can access the content." },
      { title: "Enrolment forms", body: "Multi-step application forms with document upload and payment integration." },
    ],
    stat: "78% of students research courses online before enquiring",
    relatedServices: ["Web Development", "Custom Software", "Maintenance & Support"],
  },
  {
    slug: "retail-ecommerce",
    title: "Retail & E-Commerce",
    metaTitle: "E-Commerce Development Australia | Online Stores, Stripe, Custom Builds",
    metaDescription: "Custom e-commerce stores for Australian retailers. Stripe payments, inventory, product search. No per-sale platform fees. Fixed AUD pricing from $4,500.",
    hero: "Online stores you own — with zero per-sale platform fees.",
    intro: "Shopify takes a cut of every sale. We build stores you own outright — custom product pages, Stripe checkout, inventory management and search, with no ongoing platform fees beyond hosting. For Australian retailers who want control of their margins and their data.",
    needs: [
      { title: "Stripe checkout", body: "Fast, secure checkout with Stripe — credit card, Apple Pay, Google Pay. No per-sale platform fee." },
      { title: "Product management", body: "Admin dashboard to manage products, variants, inventory levels and pricing." },
      { title: "Search & filters", body: "Fast product search with category, price and attribute filters." },
      { title: "Mobile shopping", body: "Mobile-first design — most of your customers are shopping on their phone." },
      { title: "AI recommendations", body: "Personalised product suggestions based on browsing behaviour and purchase history." },
      { title: "Order management", body: "Track orders, shipping, returns and customer communication in one place." },
    ],
    stat: "AU e-commerce hit $63B in 2025",
    relatedServices: ["Web Development", "AI & Automation", "Marketing & SEO"],
  },
  {
    slug: "finance-legal",
    title: "Finance & Legal",
    metaTitle: "Finance & Legal Web Development Australia | Compliance-Ready Sites",
    metaDescription: "Websites for Australian financial services and law firms. Compliance-ready, secure, professional. Client portals, document management, lead capture.",
    hero: "Professional sites for regulated industries.",
    intro: "Financial advisers, accountants and law firms operate under strict compliance requirements. We build sites that look professional, handle sensitive data securely, and generate leads without crossing regulatory lines — with clear disclaimers, secure client portals and content that positions your expertise.",
    needs: [
      { title: "Compliance-ready", body: "Proper disclaimers, privacy policies and consent flows baked into the build." },
      { title: "Client portals", body: "Secure areas for document sharing, case tracking and secure messaging." },
      { title: "Lead qualification", body: "Intake forms that pre-qualify enquiries before they reach your desk." },
      { title: "Content marketing", body: "Thought-leadership content, guides and FAQs that demonstrate expertise and attract organic traffic." },
      { title: "Team profiles", body: "Individual practitioner pages with specialisations, qualifications and direct contact." },
      { title: "Secure by default", body: "HTTPS, encrypted forms, secure hosting and regular security updates." },
    ],
    stat: "83% of legal clients research online before contacting a firm",
    relatedServices: ["Web Development", "Custom Software", "Marketing & SEO"],
  },
  {
    slug: "startups-saas",
    title: "Startups & SaaS",
    metaTitle: "Startup & SaaS Development Australia | MVPs, Product Builds | Build First Site",
    metaDescription: "MVP and SaaS development for Australian startups. Ship fast, iterate, scale. React, Next.js, AI. Fixed AUD pricing from $5,000.",
    hero: "Ship the MVP. Learn. Iterate.",
    intro: "Most startup ideas fail not because they are bad, but because they take too long and cost too much to test. We build MVPs and early-stage SaaS products fast, on a modern stack, so you can get in front of real users and learn before you run out of runway. Fixed pricing, full code ownership, no lock-in.",
    needs: [
      { title: "MVP builds", body: "The core workflow, built properly, in front of users in 6–8 weeks. Not a demo — a product." },
      { title: "SaaS foundations", body: "Auth, multi-tenancy, subscription billing, admin dashboards — production-ready from day one." },
      { title: "AI integration", body: "LLM-powered features, recommendation engines and automation built into the product." },
      { title: "Scalable architecture", body: "Built to handle growth — clean code, proper APIs, and infrastructure that scales with users." },
      { title: "Landing pages", body: "Pre-launch landing pages to validate demand and capture early sign-ups." },
      { title: "Iteration support", body: "Post-launch feature development, A/B testing and analytics to drive product decisions." },
    ],
    stat: "72% of startups fail due to premature scaling",
    relatedServices: ["Mobile App Development", "AI & Automation", "Custom Software"],
  },
];

export function getIndustryPage(slug) { return INDUSTRY_PAGES.find(x => x.slug === slug); }
